################# é¦–é¡µ æ ‡è¯­åŠ¨ç”» #################
banner:
  enable: true
  title: æˆ‘è§é’å±±å¤šå¦©åªšï¼Œæ–™é’å±±è§æˆ‘åº”å¦‚æ˜¯
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line


# ################# å…¬å‘Š #################
# # notice:
# #   enable: true
# #   content: Thanks for playing my game.

# ################# UI #################
# # å¯é€‰ light | dark | auto | time
# mode: auto

# ################# å­—ä½“ #################
# # head:
# #   css:
# #     fonts: https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap


# ################# å›¾ç‰‡èƒŒæ™¯ #################
# # bg_image:
#   # enable: true
#   # url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg
#   # dark:
#   # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
#   # url: https://cdn.jsdelivr.net/gh/xmuli/xmuliPic@pic/2021/back-light.jpg
#   # dark: https://cdn.jsdelivr.net/gh/xmuli/xmuliPic@pic/2021/back-dark.jpg
#   # opacity: 0.8

# ################# æœç´¢èƒŒæ™¯ #################
# # search:
# #   modal: true
# #   bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
# #   dark_bg_image: xxx
# #   # placeholder:

# ################# éšæœºå¤šè¾¹å½¢èƒŒæ™¯ #################
# trianglify:
#   enable: false
#   cellSize: 75
#   width: 800
#   height: 600
#   palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
#   opacity: 0.5

# ################# çƒŸèŠ± #################
# fireworks:
#   enable: true
#   colors:
#     - '102, 167, 221'
#     - '62, 131, 225'
#     - '33, 78, 194'

# ################# Medium Zoom æ”¾å¤§é¢„è§ˆå›¾ç‰‡ #################
# # _config.yun.yml
# medium_zoom: true

# ################# ScrollReveal #################
# scrollreveal:
#   enable: true
#   targets:
#     - .post-card
#     - .markdown-body img

# ################# Cursor å…‰æ ‡ #################
# cursor:
#   enable: false
#   default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
#   pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
#   text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

# ################# ä¾§è¾¹æ  #################
# sidebar:
#   bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
#   bg_position: bottom 3rem center
#   tagcloud:
#     enable: false
#     amount: 20

# ################# å¤´åƒ #################
# # avatar:
#   # enable: true
#   # url: /xmuli.png   # å›å¤´ç¡®è®¤è¿™ä¸ª
#   # rounded: true
#   # opacity: 1
#   # mickey_mouse: false
#   # status:
#   #   enable: true
#   #   emoji: ğŸ€
#   #   message: ä¸€ç‰‡å››å¶å¹¸è¿è‰

# ################# å¯¼èˆª #################
# menu:
#   home:
#     path: /
#     icon: ri:home-4-line
#   list:
#     - type: archives
#       path: /archives/
#       icon: ri:archive-line
#     - type: categories
#       path: /categories/
#       icon: ri:folder-2-line
#     - type: tags
#       path: /tags/
#       icon: ri:price-tag-3-line
#     # - path: https://www.yunyoujun.cn
#     #   icon: ri:cloud-line
#     #   count: ä½ çŒœ
#   custom:
#     title: æ–‡æ¡£
#     path: https://ifmet.cn/about
#     icon: ri:settings-line

# ################# é¡µé¢é“¾æ¥ #################
# # pages:
# #   - name: å‹é“¾ç›´è¾¾
# #     url: /links/
# #     icon: ri:genderless-line
# #     color: dodgerblue
# #   - name: å­¦ä¹ ä»–äºº
# #     url: /learn/
# #     icon: ri:genderless-line  # TODO
# #     color: Pink

# ################# æ–‡ç«  å†…å®¹å¡ç‰‡ #################
# post_card:
#   opacity: 0.8  # TODO æ‰©å±•ä¸ºå¡ç‰‡ï¼Œæœ‰ç‚¹æ„æ€

# ################# ä¿¡æ¯ #################
# post_meta:
#   item_text: false
#   created_at: true
#   updated_at: true
#   categories: true
#   tags: true

# ################# ç›®å½• #################
# toc:
#   list_number: true
#   max_depth: 6
#   min_depth: 1
#   placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
#   collapse: false

# ################# ç¼–è¾‘é“¾æ¥ #################
# post_edit:
#   enable: true
#   url: https://github.com/YYGraspWorld/YYGraspWorld.github.io/tree/master/source/

################# ä»£ç é«˜äº® | å¼€å¯ä¸€é”®å¤åˆ¶æŒ‰é’® #################
# å…³é—­ highlight
highlight:
  enable: false
# å¯ç”¨ prism
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# codeblock:
#   copy_btn: true

# ################# ç‰ˆæƒ #################
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

# ################# å›¾ç‰‡æ‡’åŠ è½½ #################
# lazyload:
#   enable: true

# #-------------------------------------- BRGIN ----------------------------------------
# ##################################### é¡µè„š #####################################
# # ä»¥ä¸‹é…ç½®å‡å†™åœ¨ footer å­—æ®µä¸‹ï¼Œè¯·åŒæ—¶æ”¾åˆ° footer ä¸‹ã€‚ï¼ˆåªä¿ç•™ä¸€ä¸ª footerã€‚ï¼‰ å¦‚ï¼š
# footer:      
################# èµ·å§‹å¹´ä»½ #################
  since: 2022

# ################# å›¾æ ‡ #################
#   icon:
#     name: ri:cloud-line
#     animated: true
#     color: '#0078E7'
#     url: https://google.com
#     title: å¯çˆ±çš„èµåŠ©è€…ä»¬

################# é©±åŠ¨ #################
  powered:
    enable: true

################# å¤‡æ¡ˆ #################
  beian:
    enable: false

################# è¿è¡Œæ—¶é—´ #################
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2022-08-230T00:00:00'

# #-------------------------------------- END ----------------------------------------

# ################# Say #################
# say:
#   enable: true
#   api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
#   # https://developer.hitokoto.cn/sentence/
#   hitokoto:
#     enable: true
#     api: https://v1.hitokoto.cn

# ################# è‡ªå®šä¹‰è¯­å¥ #################
# # ç•¥

# ################# Special #################
# mourn:
#   enable: false
#   days:
#     - 4-4

# ################# æ ‡ç­¾ tags #################
# wordcloud:
#   enable: false

# ################# åˆ†ç±» categories #################
# ################# å½’æ¡£ archives #################
# ################# ç›¸å†Œ albums #################
# albums:
#   enable: false

################# github_issues #################
github_issues:
  enable: true
  username: YYGraspWorld
  repository: YYGraspWorld.github.io
  filters: is:issue


# ################# æœç´¢ : å¼•æ“æœç´¢ | æœ¬åœ°æœç´¢ #################
# engine_search:
#   enable: false
#   href: 'https://www.google.com/search?q=site:'
#   # href: "https://www.baidu.com/s?wd=site:"
#   # href: "https://www.bing.com/search?q=site:"
#   domain: yygraspworld.github.io

# # search
# # https://github.com/next-theme/hexo-generator-searchdb
# local_search:
#   enable: true

#-------------------------------------- é¢å¤–ä¾èµ–åº“æ”¯æŒ BRGIN ----------------------------------------
################# å­—æ•°ç»Ÿè®¡ #################
wordcount:
  enable: true
  count: true
  time: true


